version: "3"
services:
  db:
    image: mysql:5.7
    container_name: poliservaDB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    env_file: .env
    restart: always
    volumes:
      - ./backend/db/iniDB.sql:/docker-entrypoint-initdb.d/initDB.sql
      - poliserva_mysql_data:/var/lib/mysql
    networks:
      poliserva: 
        ipv4_address: 172.29.0.10

  backend-laravel:
    build: 
      context: ./backend/
      dockerfile: ./laravel/Dockerfile
    container_name: poliservaLARAVEL
    command: sh -c './wait-for-it.sh db:3306; ./migrate.sh; php artisan serve --host=0.0.0.0 --port=8002'
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - poliserva_laravel_uploads:/app/laravel/public/uploads
      - ./backend/db/migrate.sh:/app/laravel/migrate.sh
    networks:
      poliserva: 
        ipv4_address: 172.29.0.11

  backend-go:
    build:
      context: ./backend/
      dockerfile: ./go/Dockerfile
    container_name: poliservaGO
    command: sh -c './wait-for-it.sh db:3306; go run main.go'
    ports:
      - "8003:8003"
    depends_on:
      - db
      - backend-laravel
    networks:
      poliserva: 
        ipv4_address: 172.29.0.12

networks:
  poliserva:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1

volumes:
  poliserva_mysql_data:
  poliserva_laravel_uploads: